"""Knowledge Digest model for OmegaKG Validation API.

Defines the structure of the data sent from InGest-LLM workers to OmegaKG.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime


class KnowledgeDigest(BaseModel):
    """
    Structured knowledge digest for OmegaKG validation API.

    Generated by InGest-LLM workers from processed raw data.
    """

    source_id: str
    digest_type: str  # "conversation", "terminal_event", etc.
    title: str
    content: str
    summary: Optional[str] = None
    embedding: Optional[List[float]] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    tags: List[str] = Field(default_factory=list)
    references: Dict[str, Any] = Field(default_factory=dict)
    captured_at: Optional[datetime] = None
    processed_at: datetime = Field(default_factory=datetime.utcnow)


def create_conversation_digest(
    raw_payload: dict,
    summary: str,
    vault_filepath: str,
    source_id: str,
    platform: str,
    message_count: int,
    embedding: Optional[List[float]] = None,
    captured_at: Optional[datetime] = None,
) -> KnowledgeDigest:
    """
    Create knowledge digest from processed conversation data.
    """
    # Extract messages for content preview
    messages = raw_payload.get("messages", [])
    content_preview = "\n".join(
        f"{msg.get('role', '')}: {msg.get('content', '')[:300]}"
        for msg in messages[:10]  # Take a bit more for the "content" field
    )

    # Generate title from summary
    title = summary.split(".")[0][:100] if summary else f"Conversation from {platform}"

    return KnowledgeDigest(
        source_id=source_id,
        digest_type="conversation",
        title=title,
        content=f"Platform: {platform}\n\n{content_preview}",
        summary=summary,
        embedding=embedding,
        metadata={
            "platform": platform,
            "message_count": message_count,
            "vault_path": vault_filepath,
            "original_url": raw_payload.get("url"),
        },
        tags=["ai_conversation", platform.lower()],
        references={"vault_file": vault_filepath, "url": raw_payload.get("url")},
        captured_at=captured_at or datetime.utcnow(),
    )
