"""create terminal_events table

Revision ID: 010fb5e1f71f
Revises: 003_create_raw_webhook_events
Create Date: 2026-01-03 01:14:36.703311

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "010fb5e1f71f"
down_revision = "003_create_raw_webhook_events"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_table(
        "terminal_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("cwd", sa.String(), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("host", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # Removed destructive drop commands for existing tables
    # op.drop_index(op.f('idx_heartbeat_timestamp'), table_name='system_heartbeats')
    # op.drop_table('system_heartbeats')
    # op.drop_index(op.f('idx_ingest_failures_created_at'), table_name='ingest_failures')
    # op.drop_table('ingest_failures')
    # op.drop_index(op.f('idx_omega_vectors_cleanup'), table_name='omega_vectors_1024', postgresql_where="(status = 'pending_embedding'::text)")
    # op.drop_index(op.f('idx_omega_vectors_embedding_hnsw'), table_name='omega_vectors_1024', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # op.drop_index(op.f('idx_omega_vectors_failed_retry'), table_name='omega_vectors_1024', postgresql_where="(status = 'failed'::text)")
    # op.drop_index(op.f('idx_omega_vectors_message_id'), table_name='omega_vectors_1024')
    # op.drop_index(op.f('idx_omega_vectors_neo4j_lookup'), table_name='omega_vectors_1024')
    # op.drop_index(op.f('idx_omega_vectors_node_label'), table_name='omega_vectors_1024')
    # op.drop_index(op.f('idx_omega_vectors_pending'), table_name='omega_vectors_1024', postgresql_where="(status = 'pending_embedding'::text)")
    # op.drop_index(op.f('idx_omega_vectors_status'), table_name='omega_vectors_1024')
    # op.drop_table('omega_vectors_1024')
    # op.drop_index(op.f('idx_pending_transactions'), table_name='ingest_transactions', postgresql_where="((status)::text = 'PENDING'::text)")
    # op.drop_table('ingest_transactions')
    op.alter_column(
        "raw_webhook_events",
        "error_log",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_comment="Processing error details if any",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_raw_webhook_events_processed_status"), table_name="raw_webhook_events"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_raw_webhook_events_processed_status"),
        "raw_webhook_events",
        ["processed_status"],
        unique=False,
    )
    op.alter_column(
        "raw_webhook_events",
        "error_log",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_comment="Processing error details if any",
        existing_nullable=True,
    )
    op.create_table(
        "ingest_transactions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "webhook_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['PENDING'::character varying, 'COMMITTED'::character varying, 'FAILED'::character varying]::text[])",
            name=op.f("ingest_transactions_status_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ingest_transactions_pkey")),
    )
    op.create_index(
        op.f("idx_pending_transactions"),
        "ingest_transactions",
        ["created_at"],
        unique=False,
        postgresql_where="((status)::text = 'PENDING'::text)",
    )
    op.create_table(
        "omega_vectors_1024",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "message_id",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
            comment="Neo4j elementId (string) or legacy ID",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'pending_embedding'::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "retry_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "node_label",
            sa.TEXT(),
            server_default=sa.text("'ChatMessage'::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['pending_embedding'::text, 'ready'::text, 'failed'::text])",
            name=op.f("omega_vectors_1024_status_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("omega_vectors_1024_pkey")),
        sa.UniqueConstraint(
            "message_id",
            "node_label",
            name=op.f("uq_omega_vectors_message_node"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_omega_vectors_status"), "omega_vectors_1024", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_omega_vectors_pending"),
        "omega_vectors_1024",
        ["message_id"],
        unique=False,
        postgresql_where="(status = 'pending_embedding'::text)",
    )
    op.create_index(
        op.f("idx_omega_vectors_node_label"),
        "omega_vectors_1024",
        ["node_label"],
        unique=False,
    )
    op.create_index(
        op.f("idx_omega_vectors_neo4j_lookup"),
        "omega_vectors_1024",
        ["message_id", "node_label"],
        unique=True,
    )
    op.create_index(
        op.f("idx_omega_vectors_message_id"),
        "omega_vectors_1024",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_omega_vectors_failed_retry"),
        "omega_vectors_1024",
        ["retry_count", "updated_at"],
        unique=False,
        postgresql_where="(status = 'failed'::text)",
    )
    op.create_index(
        op.f("idx_omega_vectors_embedding_hnsw"),
        "omega_vectors_1024",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("idx_omega_vectors_cleanup"),
        "omega_vectors_1024",
        ["updated_at"],
        unique=False,
        postgresql_where="(status = 'pending_embedding'::text)",
    )
    op.create_table(
        "ingest_failures",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("correlation_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ingest_failures_pkey")),
    )
    op.create_index(
        op.f("idx_ingest_failures_created_at"),
        "ingest_failures",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "system_heartbeats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "service_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "model_loaded", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("system_heartbeats_pkey")),
    )
    op.create_index(
        op.f("idx_heartbeat_timestamp"),
        "system_heartbeats",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.drop_table("terminal_events")
    op.drop_table("raw_conversations")
    # ### end Alembic commands ###
