"""add_embedding_to_raw_conversations

Revision ID: 9ee9fe3ca708
Revises: 010fb5e1f71f
Create Date: 2026-01-03 02:56:31.414965

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = "9ee9fe3ca708"
down_revision = "010fb5e1f71f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_heartbeat_timestamp'), table_name='system_heartbeats')
    # op.drop_table('system_heartbeats')
    op.add_column(
        "raw_conversations",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_conversations", "embedding")
    op.create_table(
        "system_heartbeats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "service_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "model_loaded", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("system_heartbeats_pkey")),
    )
    op.create_index(
        op.f("idx_heartbeat_timestamp"),
        "system_heartbeats",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
